# * Pustaka Tool Pentester (v4.5 Shell Edition)
class GuidedAssistant:
    def __init__(self):
        # * Database Bantuan & Cara Pakai (Interactive Syntax)
        self.helpDatabase = {
            "recon": "Reconnaissance itu langkah paling dasar buat lu yang mau coba-coba bongkar sistem orang lain tanpa ketauan. Lu bayangin aja kayak lagi nge-stalking gebetan lu lewat IG tapi ini lebih pro pake tool digital tingkat tinggi. Kita cari tau siapa owner-nya, pake server apa, alamat IP aslinya di mana, sampe DNS-nya kayak gimana. Tanpa recon lu bakal buta total pas mau nyerang karena gak tau titik lemah musuh di mana. Ibarat mau perang tapi gak bawa peta, pasti lu bakal nyasar dan akhirnya ketangkep basah sama admin. Jadi jangan pernah ngeremehin tahap pengumpulan info ini karena ini pondasi dari segala serangan lu nanti. Lu bisa liat siapa yang punya domainnya, email pendaftarnya apa, sampe record MX-nya buat tau mereka pake layanan email apa. Tool ini bakal ngumpulin semua data itu secara otomatis biar lu gak perlu cape-cape input satu-satu secara manual. Pokoknya recon itu kunci utama biar serangan lu gak zonk dan bener-bener kena sasaran yang pas. Bayangin aja kalo lu nyerang tapi salah server, kan malu-maluin banget dan malah bikin capek doang. Makanya recon alias pengintaian ini wajib banget dilakuin di awal perjalanan lu naklukin target. Keamanan target itu seringkali bocor dari hal-hal kecil yang mereka lupain pas registrasi domain atau server. Dengan recon lu bisa tau apakah target pake Cloudflare buat proteksi atau mereka bener-bener telanjang di internet. Pengetahuan itu kekuatan, makin banyak info yang lu dapet makin gampang lu nyari celah buat masuk. Jadi ketik aja !recon terus masukin domain target lu, biar asisten gw yang kerja keras cariin semua rahasianya. Lu tinggal duduk manis sambil ngopi nungguin hasilnya keluar di layar terminal ijo ini. Gak susah kan buat jadi hacker pro kalo lu tau cara stalking yang bener dan terarah kayak gini.",
            
            "nmap": "Nmap itu singkatan dari Network Mapper tapi mending lu anggep aja ini sebagai 'senter sakti' buat ngelongok isi rumah orang. Kalo target lu itu sebuah rumah, Nmap bakal kasih tau pintu mana yang kebuka, jendela mana yang gak dikunci, sampe lobang ventilasi mana yang bisa lu masuki. Tool ini legendaris banget di dunia cyber security karena akurasinya yang gila dan fiturnya yang lengkap banget. Lu bisa scan ribuan port cuma dalam itungan detik pake fitur SYN stealth scan yang gw kasih di sini. Kita cari tau service apa aja yang lagi running di server target, misal port 80 buat web atau port 22 buat SSH. Kalo port-nya open, berarti ada kemungkinan buat kita nyoba masuk lewat situ pake exploit yang pas nantinya. Tapi inget, jangan asal scan server pemerintah atau bank kalo gak mau diciduk polisi cyber, pake buat belajar aja ya bro. Nmap di ApexOmega ini udah gw setting biar outputnya simpel tapi tetep informatif buat lu yang baru belajar. Lu bisa liat banner grabbing-nya buat tau versi software yang mereka pake secara detail banget. Kalo lu tau versinya, lu tinggal cari di Google 'exploit for software version X' dan boom, dapet aksesnya deh. Teknologi Nmap ini dipake sama semua orang dari script kiddie sampe pro di NSA sana karena emang sekuat itu. Jadi jangan heran kalo !nmap jadi command favorit karena dia bener-bener buka mata lu soal infrastruktur target. Ibarat lu lagi ngetok-ngetok pintu, Nmap bakal dengerin suara di balik pintu itu buat nentuin siapa yang ada di dalem. Apakah dalemnya pake Apache, Nginx, atau malah Microsoft IIS yang kuno itu, semuanya bakal ketauan. Dengan tool ini, lu gak bakal lagi nyerang tembok beton yang gak ada lubangnya sama sekali. Lu bakal nemu jalan masuk yang paling gampang dan paling minim resiko ketauan sama sistem keamanan firewall mereka. Pokoknya !nmap itu wajib ada di toolkit lu kalo mau jadi website penakluk yang disegani di tongkrongan cyber lu.",
            
            "subdomain": "Subdomain discovery itu teknik buat nyari 'anak-anak' dari sebuah domain utama yang seringkali dilupain sama admin server. Lu bayangin domain utama itu pintu depan rumah yang dijaga ketat sama satpam galak berotot gede. Tapi biasanya admin itu teledor dan bikin pintu belakang kayak 'dev.target.com' atau 'test.target.com' yang gak dijaga sama sekali. Nah, tool !subdomain ini gunanya buat nyari pintu-pintu rahasia itu pake teknik brute-force yang kenceng banget. Kita tebak ribuan kombinasi nama subdomain dari yang paling umum sampe yang paling aneh buat nemu yang aktif. Kalo kita nemu subdomain yang lagi tahap development, biasanya di situ banyak bug alias celah keamanan yang bisa kita mainin. Subdomain admin atau portal secure juga seringkali bocor lewat teknik ini karena admin ngerasa gak bakal ada yang tau link-nya. Padahal di dunia cyber, gak ada yang bener-bener rahasia kalo lu punya worldlist yang mantap dan threading yang cepet. Tool ini bakal nyoba konek ke subdomain kayak mail, ftp, vpn, sampe staging environment yang biasanya isinya data-data sensitif banget. Lu bisa nemu server database yang gak diproteksi atau panel kontrol yang lupa dikasih password di subdomain rahasia ini. Sering banget hacker pro dapet akses root cuma gara-gara nemu subdomain 'backup' yang isinya file zip database asli. Jadi jangan cuma fokus di www doang, cari juga semua anak-anaknya biar target lu gak punya tempat sembunyi lagi. Prosesnya otomatis kok, lu tinggal input domainnya terus tool ini bakal lari nyisir semua kemungkinan dalam waktu singkat. Outputnya bakal muncul di tab Roadmap lu dan nambahin centang buat misi subdomain discovery yang udah selesai lu jalanin. Makin banyak subdomain yang lu dapet, makin besar peluang lu nemu server yang bener-bener rentan dan gampang buat dieksploitasi. Ini taktik standar yang dipake di Kali Linux buat 'expand the attack surface' alias memperluas wilayah serangan lu. Jadi gaskeun pake !subdomain biar lu tau betapa luasnya kerajaan digital yang lagi lu incer sekarang juga.",
            
            "webaudit": "Web Audit itu proses buat meriksa kesehatan keamanan website target lu secara menyeluruh kayak disuntik dokter. Kita cek dari kepala sampe kaki, mulai dari headers, cookies, sampe script-script rahasia yang jalan di dalem browser-nya. Tool !webaudit di ApexOmega ini udah pake mesin Nitro yang bisa deteksi WAF (Web Application Firewall) kayak Cloudflare secara otomatis. Kalo ada WAF, lu harus hati-hati karena serangan kasar lu bakal langsung diblokir dan IP lu bisa masuk blacklist mereka. Tapi tenang, webaudit juga bakal ngasih tau teknologi apa aja yang dipake di sana, misal React, Vue, atau PHP versi jadul. Kita juga bakal audit cookie-nya, liat apakah udah ada flag httponly sama secure biar gak bisa dicuri pake teknik session hijacking. Selain itu, webaudit bakal nge-fuzzing directory buat nyari folder 'harta karun' kayak /admin, /config, atau folder /git yang isinya source code. Lu juga bakal dikasih tau kalo header keamanannya kurang lengkap, misalnya gak ada X-Frame-Options yang bikin web itu kena Clickjacking. Semua info ini disajiin dalam format yang jelas banget biar lu tau apa yang harus lu serang duluan nanti. Prosesnya deep banget karena kita bener-bener nge-parse HTML target buat nyari link-link tersembunyi yang gak keliatan sama user biasa. Lu juga bisa liat respon dari server secara live kayak di menu inspect element console di browser Google Chrome gitu deh. Pokoknya webaudit itu otak dari segala audit website lu karena di sinilah semua data dikumpulin jadi satu kesimpulan. Lu bakal tau target lu itu 'empuk' atau 'keras' setelah liat hasil dari command sakti !webaudit ini di layar console. Hacker yang pinter itu gak langsung nyerang, tapi dia audit dulu sampe mateng biarr sekali tembak langsung tembus targetnya. Jangan males buat baca hasil log-nya ya bro, karena seringkali celah paling gede itu nyempil di baris log yang paling bawah. Dengan Nitro Web Audit v5.0, lu udah selangkah lebih maju daripada hacker amatiran yang cuma tau cara ddos doang tapi gak tau cara audit. Yuk sikat target lu pake !webaudit dan liat betapa banyak lubang yang mereka punya di sistem keamanannya sekarang.",
            
            "vuln": "Vuln Atlas itu peta harta karun buat lu yang pengen tau di mana letak persisnya 'lubang' alias vulnerability di website target. Kita khususin tool ini buat nyari celah-celah elit yang bukan kaleng-kaleng kayak SQL Injection, XSS, sampe CSRF yang berbahaya banget. Lu bisa bayangin Vuln Atlas itu kayak detektor logam yang bunyi kenceng tiap kali nemu sesuatu yang berharga di dalem tanah. Kita tes ratusan payload secara otomatis ke semua parameter yang ada di URL target lu tanpa perlu pusing mikirin syntax-nya. Kalo ada payload yang tembus, sistem bakal langsung kasih notifikasi ijo yang artinya target lu itu bener-bener 'vulnerable' alias rentan. Kita juga cek kerentanan Host Header Injection yang bisa bikin user lain kena tipu lewat redirect palsu yang kita bikin. Selain itu ada audit CORS buat liat apakah data pribadi user bisa dicuri sama website lain yang nakal gara-gara adminnya asal setting origin. Vuln Atlas juga punya fitur Fuzzing Sensitive Paths yang bakal nyisir 50+ file rahasia kayak .env, config.php, sampe id_rsa key. Kalo lu nemu file .env yang isinya password database, itu artinya lu udah menang telak dan bisa kuasain servernya detik itu juga. Tool ini dirancang biar hasilnya 'bener-bener jelas' kayak yang lu mau, jadi lu gak perlu bingung lagi mana celah beneran mana yang zonk. Setiap celah yang ditemuin bakal gw kasih tau juga tingkat bahayanya, apakah itu Critical, High, atau cuma Medium/Low risk doang. Misi vuln audit ini jadi penentu apakah lu bisa lanjut ke tahap eksploitasi atau lu harus nyari target lain yang lebih gampang ditembus. Jangan pernah nyerah kalo scan pertama gak nemu apa-apa, coba pake payload lain atau ganti ke mode brutal yang udah gw sediain. Dunia pwn itu soal kesabaran dan ketelitian buat nyari satu titik lemah dari jutaan baris kode yang rumit banget. Tapi dengan bantuan Vuln Atlas di ApexOmega v5.0, tugas lu jadi jauh lebih enteng karena semua proses beratnya udah gw otomatisasiin total. Lu tinggal fokus buat mikirin gimana cara masukin payload kreatif lu ke dalem form input target biar dapet akses administrator segera. Gaskeun pake !vuln dan buktiin kalo lu emang penakluk website yang handal di manapun lu berada sekarang.",
            
            "api": "API Auditor itu spesialis buat ngebongkar rahasia di balik layar aplikasi modern yang biasanya pake koneksi REST atau GraphQL. Jaman sekarang website itu cuma 'topeng' doang, sebenernya semua datanya ngalir lewat jalur API yang seringkali lupa gak dikasih pengaman. Nah, !api ini bakal nyisir semua jalur rahasia itu, mulai dari endpoint /api/v1, /v2, sampe jalur documentation kayak Swagger yang isinya bocoran. Kita tes satu-satu setiap endpoint itu buat liat apakah kita bisa dapet data user tanpa perlu login alias teknik IDOR yang legendaris itu. Tool ini juga bakal nge-fuzzing HTTP Methods buat tau apakah kita bisa ngirim request POST atau DELETE ke tempat yang harusnya cuma buat GET. Bayangin kalo lu bisa nge-delete data orang cuma gara-gara adminnya lupa gak nutup akses method DELETE di API user-nya. API Auditor bakal ngasih tau semua celah itu secara live dan transparan biar lu bisa langsung hajar titik lemahnya yang paling parah. Sering banget API itu ngasih informasi yang terlalu banyak (Excessive Data Exposure) yang harusnya gak boleh diliat sama publik. Kita cek juga apakah ada token JWT yang bocor atau API Key yang kesimpen di file-file JavaScript yang bisa kita scrap pake tool ini. Audit API itu jadi wajib karena jaman sekarang hampir semua website udah pindah ke sistem microservices yang saling konek lewat API. Kalo lu bisa naklukin satu API aja, biasanya lu bisa dapet akses ke semua database di belakangnya tanpa hambatan sama sekali. Jadi jangan cuma liat tampilan depan website-nya aja bro, liat juga 'urat nadi' digitalnya lewat command !api yang sakti mandraguna ini. Hasilnya bakal nambahin progres di Roadmap lu dan bikin misi pentesting lu makin lengkap dan keliatan professional banget. Inget ya, API yang gak aman itu ibarat lu ninggalin kunci gudang di bawah keset depan rumah, gampang banget buat dicari dan diambil. Makanya pake API Auditor buat mastiin target lu emang punya pengamanan yang bener atau cuma asal-asalan bikin doang. Kalo lu nemu celah di API, itu artinya lu udah dapet 'VIP Pass' buat masuk ke sistem inti mereka tanpa perlu repot-repot tembusin firewall depan. Gaskeun audit API target lu sekarang juga dan liat betapa banyak data rahasia yang bisa lu dapet lewat jalur belakang ini.",
            
            "cloud": "Cloud Hunter itu tool pencium 'bau' data bocor di awan alias layanan cloud storage kayak AWS S3, Firebase, atau Google Cloud. Admin jaman now suka banget nitip file-file penting di cloud tapi seringkali mereka bego dan nyetting aksesnya jadi 'Public' buat siapa aja. Tool !cloud ini bakal nyari bucket-bucket itu secara otomatis cuma bermodalkan nama domain target yang lagi lu incer sekarang juga. Kita tebak puluhan kombinasi nama bucket yang mungkin dipake sama perusahaan target lu buat nyirpen data backup, source code, atau database. Kalo kita nemu satu aja bucket yang public, itu isinya bisa jutaan record data user yang bakal bikin lu jadi sultan cyber dalam sekejap. Firebase Database yang gak diproteksi juga seringkali jadi sasaran empuk karena isinya biasanya data chat, email, sama password user yang plain text. Hunter ini pake teknik rekursif yang pinter banget buat mastiin gak ada satupun layanan cloud target yang lu lewatin pas proses recon. Seringkali celah keamanan paling gila itu bukan di website utamanya, tapi malah di bucket S3 tempat mereka nyimpen file-file lama yang lupa diapus. Lu bisa nemu file kunci SSH, credential database, sampe dokumen internal perusahaan yang harusnya rahasia banget di dalem sana. Proses scan-nya cepet banget karena kita cuma nge-ping endpoint cloud provider yang udah kita list secara rahasia di sistem internal. Kalo dapet hasil ijo berarti jackpot bro, lu tinggal buka link-nya dan lu bisa download semua data itu sepuas lu tanpa batas. Ini teknik recon elit yang jarang diketahui sama hacker pemula karena mereka biasanya cuma fokus di script-script web doang. Tapi buat lu yang pake ApexOmega v5.0, lu bisa jadi Hunter professional yang bisa nemu data di mana aja bahkan di langit (cloud) sekalipun. Setiap bucket yang lu temuin bakal dicatet dan lu bisa pamerin hasilnya di laporan audit lu nanti biar keliatan makin sangar. Pokoknya jangan pernah skip tahap cloud hunting ini kalo lu mau dapetin hasil maksimal dari misi penaklukan website lu sekarang. Cloud itu aman kalo dipake bener, tapi bakal jadi petaka buat owner-nya kalo mereka males setting permission yang bener di dalem konsol manajemen cloud-nya. Yuk gaskeun pake !cloud dan liat apakah target lu punya simpenan rahasia di awan yang bisa lu ambil sekarang juga.",
            
            "stress": "Stress Testing itu modul buat ngetes seberapa kuat 'mental' server target lu pas dihajar ribuan request secara bersamaan dalam waktu singkat. Lu bisa anggap tool !stress ini sebagai serangan gelombang tsunami digital yang bakal bikin server target lu kelabakan dan akhirnya tumbang alias offline. Kita pake teknik Layer 7 HTTP Flood yang udah dimodifikasi biar bisa bypass sistem caching dan WAF yang ada di depan server-nya. Dengan fitur Nitro Engine, kita gerakin puluhan thread secara barengan buat ngirim paket-paket request massal yang bikin CPU server mereka jadi 100%. Lu bisa setting durasi sama jumlah pasukannya (threads) sesuka hati lu buat nentuin seberapa parah kerusakan yang mau lu bikin di sana. Inget ya bro, pake tool ini buat ngetes kekuatan server lu sendiri aja atau buat belajar gimana cara mitigasi serangan DDoS yang makin brutal. Kalo server target lu emang lemah, sekali pencet !stress dia pasti langsung 'megap-megap' dan gak bisa dibuka sama sekali oleh user aslinya. Tool ini pake teknik bypass 'Cache Buster' yang unik banget, jadi setiap request yang kita kirim itu isinya selalu beda biar server harus mikir keras terus. Selain itu kita juga pake random User-Agent sama IP palsu (X-Forwarded-For) biar administrasi server mereka bingung siapa penyerang aslinya. Stress testing v5.0 ini bener-bener dirancang buat performa brutal yang bisa bikin server Apache atau Nginx versi lama langsung nyungsep detik itu juga. Hasilnya bakal keliatan secara live di layar ijo lu, lu bisa liat progres request yang ke-sent dan status respon dari server target lu secara langsung. Kalo target lu tewas, biasanya Roadmap Checklist langkah nomor 6 bakal otomatis ke-centang sebagai tanda misi penaklukan lu udah tuntas sampe akar-akarnya. Lu udah bener-bener jadi master website karena udah bisa audit teknisnya sampe bisa 'mematikan' layanannya secara total lewat command sakti ini. Tapi tetep ya bro, do it with responsibility, jangan bikin kacau infrastruktur penting milik publik cuma gara-gara mau pamer kekuatan doang di grup. Pake !stress buat buktiin kalo lu emang punya toolkit yang selevel sama tool militer cyber tingkat tinggi yang ada di film-film hacker itu. Server yang kuat itu harus tahan banting dari segala arah, dan lu lah yang ngetes apakah mereka emang sekuat itu atau cuma modal gaya doang padahal ringkih."
        }
        
        # * Pentesting Roadmap Checklist Steps v5.0
        self.roadmap = [
            "v5.0-STEP-1: Information Gathering (!recon) - Cari info dasar target biar gak buta pas nyerang.",
            "v5.0-STEP-2: Infrastructure Scan (!nmap) - Scan pintu-pintu masuk (port) yang lagi kebuka di server.",
            "v5.0-STEP-3: Subdomain Discovery (!subdomain) - Cari pintu belakang rahasia di anak-anak domain utama.",
            "v5.0-STEP-4: Vulnerability Audit (!webaudit / !vuln) - Cari lubang keamanan kayak SQLi atau XSS biar bisa masuk.",
            "v5.0-STEP-5: API & Cloud Hunting (!api / !cloud) - Bongkar jalur data rahasia sama storage yang bocor ke publik.",
            "v5.0-STEP-6: Stress Testing (!stress) - Tes mental server target sampe lemes alias offline total buat finish."
        ]

    def getSteps(self):
        return []

    def getRoadmap(self):
        return self.roadmap

    def searchHelp(self, query):
        query = query.lower()
        results = {}
        for k, v in self.helpDatabase.items():
            if query in k or query in v.lower():
                results[k] = v
        return results
